# Generated by Django 4.2.4 on 2023-08-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date']},
        ),
    ]
